site_name: junior.guru
site_url: https://junior.guru/


nav:
  - Klub:
      - Klub: club.md
      - Rozcestník pro členy: membership.jinja
      - Klubové lekce angličtiny: membership-english.jinja
  - Příručka:
      - Cesta juniora: handbook/index.md
      - Proč programovat: handbook/motivation.md
      - Mýty: handbook/myths.md
      - Ženy v IT: handbook/women.md
      - Rodiče v IT: handbook/parents.md
      - Základy: handbook/learn.md
      - Bez kódu: handbook/nocode.md
      - Angličtina: handbook/english.md
      - Vybírání kurzu: handbook/course.md
      - Řešení problémů: handbook/help.md
      - První praxe: handbook/practice.md
      - Psychika: handbook/mental-health.md
      - Git a GitHub: handbook/git.md
      - Hledání práce: handbook/candidate.md
      - Životopis: handbook/cv.md
      - LinkedIn: handbook/linkedin.md
      - Pohovor: handbook/interview.md
  - Kurzy:
      - Kurzy programování: courses.md
      - ... | flat | courses/*.md
  - Práce: jobs/
  - Novinky:
      - Novinky: news.jinja
      - Podcast:
          - Podcast: podcast.md
          - ... | flat | podcast/*.jinja
      - Klubové akce:
          - Klubové akce: events.md
          - ... | flat | events/*.md
      - Příběhy:
          - Příběhy: stories.md
          - ... | flat | stories/*.md
      - Moudra: wisdom.jinja

  - Pravidla:
      - Otázky a odpovědi: faq.md
      - Pravidla chování: coc.md
      - Obchodní podmínky: tos.md
      - Zásady ochrany osobních údajů: privacy.md
      - Čísla a grafy: open.md
      - Licence obsahu (CC BY-SA): https://creativecommons.org/licenses/by-sa/4.0/deed.cs
  - Témata:
      - ... | flat | topics/*.md
  - Partnerství:
      - ... | flat | open/*.md
  - Připravované:
      - ... | flat | handbook/*.md
  - Ostatní:
      - ... | flat


validation:
  absolute_links: ignore


markdown_extensions:
  - toc:
      toc_depth: '2-2'
      permalink: '#'
      permalink_title: Odkaz na tuto sekci
  - tables
  - fenced_code
  - attr_list


theme:
  name: null
  custom_dir: theme/


hooks:
  - hooks.py


plugins:
  - gen-files:
      scripts:
        - templates.py
  - awesome-pages:
      strict: true


# Removed 'strict', because it gives warnings if linking non-existing targets. Once the Flask
# app is gone, 'strict' should return to be enabled.
#strict: true
