version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Europe/Prague
  open-pull-requests-limit: 1
  labels:
  - dependencies
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Europe/Prague
  open-pull-requests-limit: 1
  labels:
  - dependencies
