[tool.poetry]
name = "juniorguru"
version = "0.0.0"
description = "Learn to code and get your first job in tech 🐣"
authors = ["Honza Javorek <honza@junior.guru>"]
license = "MIT"
readme = "README.md"
homepage = "https://junior.guru/"
repository = "https://github.com/juniorguru/junior.guru/"

[tool.poetry.scripts]
jg = "juniorguru.cli:main"

[tool.poetry.dependencies]
python = "3.11.*"
jinja2 = "3.1.3"
gspread = "5.12.4"
oauth2client = "4.1.3"
arrow = "1.3.0"
markdown = "<3.6"  # mkdocs depend on <3.5
flask = "3.0.0"
frozen-flask = "1.0.1"
pillow = "10.2.0"
peewee = "3.17.1"
strictyaml = "1.7.3"
lxml = "4.9.3"
cssselect = "1.2.0"
google-api-python-client = "2.111.0"
requests = "2.31.0"
fiobank = "3.0.0"
emoji = "2.7.0"
favicon = "0.7.0"
feedparser = "6.0.10"
py-cord = {version = "2.4.1", extras = ["speed"]}
gql = {extras = ["requests"], version = "3.5.0"}
mkdocs = "1.5.2"
markupsafe = "2.1.3"
ics = {version = "0.8.0.dev0", allow-prereleases = true}
pod2gen = "1.0.3"
python-slugify = "8.0.2"
playwright = "1.41.1"
click = "8.1.7"
mkdocs-gen-files = "0.5.0"
mkdocs-awesome-pages-plugin = "2.9.2"
juniorguru-chick = { git = "https://github.com/juniorguru/chick.git" }
pycircleci = "0.7.0"
livereload = "2.6.3"
beautifulsoup4 = "4.12.2"
czech-sort = "1.1.0"
teemup = "1.0.1"
stripe = "8.1.0"
diskcache = "5.6.3"
apify-client = "1.6.1"
apify-shared = "1.1.0"
langdetect = "1.0.9"
w3lib = "2.1.2"
openai = "1.9.0"
tenacity = "8.2.3"

[tool.poetry.group.dev.dependencies]
pytest = "7.4.2"
pync = "2.0.3"
flake8 = "6.1.0"
isort = "5.13.2"
sqlite-utils = "3.36"
ghp-import = "2.1.0"
pytest-asyncio = "0.23.4"
scour = "0.38.2"
black = "23.9.1"
datasette = {version = "1.0a7", allow-prereleases = true}

[tool.pytest.ini_options]
python_files = "test_*.py *_test.py test.py"
testpaths = "."
norecursedirs = "node_modules jobs_legacy"
addopts = "--ff"
filterwarnings = [
    "ignore:'audioop' is deprecated:DeprecationWarning",
]

[tool.black]
target-versions = ["py311"]
include = "\\.py$"
exclude = """(\
juniorguru/[^_]+_legacy|\
node_modules\
)"""

[tool.isort]
profile = "black"
lines_after_imports = 2
combine_as_imports = true
extend_skip = ["jobs_legacy"]
known_local_folder = ["testing_utils"]

[build-system]
requires = ["poetry-core>=1.5.0"]
build-backend = "poetry.core.masonry.api"
